#define _DARWIN_C_SOURCE

#include "ds4_gpu.h"

#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define QSA_INDEX_HEADS 4u
#define QSA_INDEX_DIM 128u
#define QSA_BLOCK 4u
#define QSA_BLOCKS 8u
#define QSA_INDEX_TOKENS (QSA_BLOCKS * QSA_BLOCK)
#define QSA_HEADS 24u
#define QSA_KV_HEADS 2u
#define QSA_HEAD_DIM 256u
#define QSA_CACHE_CAPACITY 32u
#define QSA_POSITION 22u
#define QSA_SELECTED_BLOCKS 3u

bool ds4_log_is_tty(FILE *fp) {
    (void)fp;
    return false;
}

static float fixture_value(uint64_t index, uint32_t salt, float scale) {
    const int32_t centered =
        (int32_t)((index * (19u + salt) + salt * 37u) % 509u) - 254;
    return (float)centered * scale;
}

static float sigmoid_ref(float x) {
    if (x >= 0.0f) return 1.0f / (1.0f + expf(-x));
    const float e = expf(x);
    return e / (1.0f + e);
}

static float cache_value(const void *cache, uint64_t index, bool f16) {
    return f16 ? (float)((const _Float16 *)cache)[index]
               : ((const float *)cache)[index];
}

static void cache_store(void *cache, uint64_t index, bool f16, float value) {
    if (f16) (( _Float16 *)cache)[index] = (_Float16)value;
    else ((float *)cache)[index] = value;
}

static void rope_pair_ref(float x0, float x1, uint32_t pair,
                          uint32_t position,
                          const ds4_gpu_qwen4_exp_rope_params *rope,
                          float *out0, float *out1) {
    const float exponent = -2.0f * (float)pair / (float)rope->n_rot;
    const float theta_extrap = (float)position * powf(rope->freq_base, exponent);
    float theta = rope->freq_scale * theta_extrap;
    float mscale = rope->attn_factor;
    if (rope->ext_factor != 0.0f) {
        const float two_pi = 6.2831853071795864769f;
        const float denom = 2.0f * logf(rope->freq_base);
        const float low_raw = (float)rope->n_rot *
            logf((float)rope->n_ctx_orig / (rope->beta_fast * two_pi)) / denom;
        const float high_raw = (float)rope->n_rot *
            logf((float)rope->n_ctx_orig / (rope->beta_slow * two_pi)) / denom;
        const float low = fmaxf(0.0f, floorf(low_raw));
        const float high = fminf((float)rope->n_rot - 1.0f, ceilf(high_raw));
        const float y = ((float)pair - low) / fmaxf(0.001f, high - low);
        const float ramp = 1.0f - fminf(1.0f, fmaxf(0.0f, y));
        const float mix = ramp * rope->ext_factor;
        theta = theta * (1.0f - mix) + theta_extrap * mix;
        mscale *= 1.0f + 0.1f * logf(1.0f / rope->freq_scale);
    }
    const float c = cosf(theta) * mscale;
    const float s = sinf(theta) * mscale;
    *out0 = x0 * c - x1 * s;
    *out1 = x0 * s + x1 * c;
}

static void rope_prefix_ref(float *row, uint32_t position,
                            const ds4_gpu_qwen4_exp_rope_params *rope) {
    const uint32_t half = rope->n_rot / 2u;
    float input[QSA_INDEX_DIM];
    memcpy(input, row, sizeof(input));
    for (uint32_t pair = 0; pair < half; pair++) {
        rope_pair_ref(input[pair], input[pair + half], pair, position,
                      rope, &row[pair], &row[pair + half]);
    }
}

static int compare_values(const char *name, const float *actual,
                          const float *expected, uint64_t count,
                          float tolerance) {
    float max_abs = 0.0f;
    double sum_sq = 0.0;
    uint64_t max_index = 0;
    for (uint64_t i = 0; i < count; i++) {
        if (!isfinite(actual[i]) || !isfinite(expected[i])) {
            fprintf(stderr, "Qwen4Exp QSA %s non-finite at %llu\n",
                    name, (unsigned long long)i);
            return 0;
        }
        const float error = fabsf(actual[i] - expected[i]);
        if (error > max_abs) {
            max_abs = error;
            max_index = i;
        }
        sum_sq += (double)error * error;
    }
    fprintf(stderr,
            "Qwen4Exp QSA %-20s max_abs=%g rms=%g at=%llu tolerance=%g\n",
            name, max_abs, sqrt(sum_sq / (double)count),
            (unsigned long long)max_index, tolerance);
    return max_abs <= tolerance;
}

static int compare_long_yarn_golden(const float *actual) {
    /* Generated by the authoritative qwen4exp RotaryEmbedding on MLX and
     * cross-checked there against mlx-lm YarnRoPE at position 1,048,575. */
    static const uint32_t dims[] = {
        0, 1, 2, 3, 30, 31, 32, 33, 34, 35, 62, 63, 64, 127
    };
    static const float expected[QSA_INDEX_HEADS][14] = {
        {-0.914531052f, -0.666417718f, 0.181594431f, 0.734321177f,
         -2.0386405f, -1.80582976f, -1.24289811f, 1.17119622f,
         1.19355655f, 0.874938905f, 0.590952277f, 0.869331717f,
         1.01648402f, 1.64868259f},
        {-1.13560772f, 2.05611229f, 0.646079123f, -1.20982635f,
         0.438954949f, 0.619680882f, 1.90325928f, -0.412820101f,
         -1.91766167f, -1.59283626f, -1.16901827f, -0.955399632f,
         -0.672621131f, 0.118512578f},
        {-0.430809468f, -0.882498145f, -0.285819948f, 0.344086379f,
         -1.7061305f, -1.46738231f, -1.17863405f, 0.739143491f,
         1.09262657f, 1.14278436f, 0.920421481f, 1.18582618f,
         1.27844381f, -1.3952986f},
        {-0.661126792f, 1.84925473f, 0.172118783f, -1.6199801f,
         0.761358678f, 0.953773677f, 1.97724509f, -0.850079656f,
         -2.03053999f, -1.32346368f, -0.834200025f, -0.62745595f,
         -0.395574212f, 0.380113602f},
    };
    float max_abs = 0.0f;
    uint32_t max_head = 0;
    uint32_t max_dim = 0;
    for (uint32_t h = 0; h < QSA_INDEX_HEADS; h++) {
        for (uint32_t j = 0; j < 14u; j++) {
            const float error = fabsf(
                actual[(uint64_t)h * QSA_INDEX_DIM + dims[j]] - expected[h][j]);
            if (error > max_abs) {
                max_abs = error;
                max_head = h;
                max_dim = dims[j];
            }
        }
    }
    fprintf(stderr,
            "Qwen4Exp QSA long YaRN golden     max_abs=%g head=%u dim=%u tolerance=5e-5\n",
            max_abs, max_head, max_dim);
    return max_abs <= 5.0e-5f;
}

static void pool_block_ref(float *out, const void *raw_keys, bool f16,
                           const float *norm, uint32_t block, float eps,
                           const ds4_gpu_qwen4_exp_rope_params *rope) {
    float mean[QSA_INDEX_DIM];
    float sum_sq = 0.0f;
    for (uint32_t d = 0; d < QSA_INDEX_DIM; d++) {
        float sum = 0.0f;
        for (uint32_t r = 0; r < QSA_BLOCK; r++) {
            const uint64_t index =
                ((uint64_t)block * QSA_BLOCK + r) * QSA_INDEX_DIM + d;
            sum += cache_value(raw_keys, index, f16);
        }
        mean[d] = 0.25f * sum;
        if (f16) mean[d] = (float)(_Float16)mean[d];
        sum_sq += mean[d] * mean[d];
    }
    const float inv_rms = 1.0f / sqrtf(sum_sq / QSA_INDEX_DIM + eps);
    for (uint32_t d = 0; d < QSA_INDEX_DIM; d++) {
        out[d] = mean[d] * inv_rms * norm[d];
    }
    rope_prefix_ref(out, block * QSA_BLOCK, rope);
    if (f16) {
        for (uint32_t d = 0; d < QSA_INDEX_DIM; d++) {
            out[d] = (float)(_Float16)out[d];
        }
    }
}

static void prepare_query_ref(float *out, const float *raw_query,
                              const float *norm, uint32_t position, float eps,
                              const ds4_gpu_qwen4_exp_rope_params *rope) {
    for (uint32_t h = 0; h < QSA_INDEX_HEADS; h++) {
        const float *input = raw_query + (uint64_t)h * QSA_INDEX_DIM;
        float *row = out + (uint64_t)h * QSA_INDEX_DIM;
        float sum_sq = 0.0f;
        for (uint32_t d = 0; d < QSA_INDEX_DIM; d++) {
            sum_sq += input[d] * input[d];
        }
        const float inv_rms = 1.0f / sqrtf(sum_sq / QSA_INDEX_DIM + eps);
        for (uint32_t d = 0; d < QSA_INDEX_DIM; d++) {
            row[d] = input[d] * inv_rms * norm[d];
        }
        rope_prefix_ref(row, position, rope);
    }
}

static void score_blocks_ref(float *scores, const float *query,
                             const void *pooled, bool f16,
                             uint32_t n_blocks) {
    for (uint32_t block = 0; block < n_blocks; block++) {
        float score = 0.0f;
        for (uint32_t h = 0; h < QSA_INDEX_HEADS; h++) {
            float dot = 0.0f;
            const float *q = query + (uint64_t)h * QSA_INDEX_DIM;
            for (uint32_t d = 0; d < QSA_INDEX_DIM; d++) {
                dot += q[d] * cache_value(
                    pooled, (uint64_t)block * QSA_INDEX_DIM + d, f16);
            }
            score += fmaxf(dot, 0.0f);
        }
        scores[block] = score / sqrtf((float)QSA_INDEX_DIM);
    }
}

static int run_indexer_test(const void *model, uint64_t model_size,
                            uint64_t key_norm_offset,
                            uint64_t query_norm_offset, bool f16,
                            const ds4_gpu_qwen4_exp_rope_params *rope) {
    const uint64_t raw_count = (uint64_t)QSA_INDEX_TOKENS * QSA_INDEX_DIM;
    const uint64_t pooled_count = (uint64_t)QSA_BLOCKS * QSA_INDEX_DIM;
    const uint64_t query_count = (uint64_t)QSA_INDEX_HEADS * QSA_INDEX_DIM;
    const size_t element_bytes = f16 ? sizeof(_Float16) : sizeof(float);
    void *raw = calloc((size_t)raw_count, element_bytes);
    void *pooled_host = calloc((size_t)pooled_count, element_bytes);
    float *raw_query = malloc((size_t)query_count * sizeof(float));
    float *prepared = malloc((size_t)query_count * sizeof(float));
    float *expected_prepared = malloc((size_t)query_count * sizeof(float));
    float *scores = malloc(QSA_BLOCKS * sizeof(float));
    float *expected_scores = malloc(QSA_BLOCKS * sizeof(float));
    float *expected_block = malloc(QSA_INDEX_DIM * sizeof(float));
    float *actual_float = malloc((size_t)pooled_count * sizeof(float));
    if (!raw || !pooled_host || !raw_query || !prepared ||
        !expected_prepared || !scores || !expected_scores ||
        !expected_block || !actual_float) {
        fprintf(stderr, "Qwen4Exp QSA indexer host allocation failed\n");
        return 0;
    }
    for (uint64_t i = 0; i < raw_count; i++) {
        cache_store(raw, i, f16, fixture_value(i, f16 ? 5u : 3u,
                                               1.0f / 256.0f));
    }
    for (uint64_t i = 0; i < query_count; i++) {
        raw_query[i] = fixture_value(i, 7u, 1.0f / 192.0f);
    }

    ds4_gpu_tensor *raw_tensor = ds4_gpu_tensor_alloc(raw_count * element_bytes);
    ds4_gpu_tensor *pooled_tensor = ds4_gpu_tensor_alloc(pooled_count * element_bytes);
    ds4_gpu_tensor *raw_query_tensor = ds4_gpu_tensor_alloc(query_count * sizeof(float));
    ds4_gpu_tensor *prepared_tensor = ds4_gpu_tensor_alloc(query_count * sizeof(float));
    ds4_gpu_tensor *score_tensor = ds4_gpu_tensor_alloc(QSA_BLOCKS * sizeof(float));
    int ok = raw_tensor && pooled_tensor && raw_query_tensor &&
             prepared_tensor && score_tensor;
    ok = ok && ds4_gpu_tensor_write(raw_tensor, 0, raw,
                                    raw_count * element_bytes);
    ok = ok && ds4_gpu_tensor_write(raw_query_tensor, 0, raw_query,
                                    query_count * sizeof(float));
    for (uint32_t block = 0; block < QSA_BLOCKS && ok; block++) {
        ok = ds4_gpu_qwen4_exp_qsa_pool_block_tensor(
            pooled_tensor, raw_tensor, model, model_size, key_norm_offset,
            block, f16, 1.0e-6f, rope);
    }
    ok = ok && ds4_gpu_tensor_read(pooled_tensor, 0, pooled_host,
                                   pooled_count * element_bytes);
    const float *key_norm = (const float *)
        ((const uint8_t *)model + key_norm_offset);
    for (uint32_t block = 0; block < QSA_BLOCKS && ok; block++) {
        pool_block_ref(expected_block, raw, f16, key_norm, block,
                       1.0e-6f, rope);
        for (uint32_t d = 0; d < QSA_INDEX_DIM; d++) {
            actual_float[(uint64_t)block * QSA_INDEX_DIM + d] =
                cache_value(pooled_host,
                            (uint64_t)block * QSA_INDEX_DIM + d, f16);
        }
        char label[48];
        snprintf(label, sizeof(label), "pool %s block %u",
                 f16 ? "F16" : "F32", block);
        ok = compare_values(label,
            actual_float + (uint64_t)block * QSA_INDEX_DIM,
            expected_block, QSA_INDEX_DIM, f16 ? 1.0e-3f : 1.0e-4f);
    }

    /* The pooled cache is derived state.  Rewriting raw rows after a rollback
     * must only require overwriting the affected completed block. */
    uint8_t block0_before[QSA_INDEX_DIM * sizeof(float)];
    const size_t pooled_row_bytes = QSA_INDEX_DIM * element_bytes;
    memcpy(block0_before, pooled_host, pooled_row_bytes);
    for (uint32_t r = 0; r < QSA_BLOCK; r++) {
        for (uint32_t d = 0; d < QSA_INDEX_DIM; d++) {
            const uint64_t index = ((uint64_t)QSA_BLOCK + r) * QSA_INDEX_DIM + d;
            cache_store(raw, index, f16,
                        fixture_value(index, 31u, 1.0f / 128.0f));
        }
    }
    ok = ok && ds4_gpu_tensor_write(raw_tensor,
        (uint64_t)QSA_BLOCK * QSA_INDEX_DIM * element_bytes,
        (const uint8_t *)raw +
            (uint64_t)QSA_BLOCK * QSA_INDEX_DIM * element_bytes,
        QSA_BLOCK * QSA_INDEX_DIM * element_bytes);
    ok = ok && ds4_gpu_qwen4_exp_qsa_pool_block_tensor(
        pooled_tensor, raw_tensor, model, model_size, key_norm_offset,
        1, f16, 1.0e-6f, rope);
    ok = ok && ds4_gpu_tensor_read(pooled_tensor, 0, pooled_host,
                                   pooled_count * element_bytes);
    if (ok && memcmp(block0_before, pooled_host, pooled_row_bytes) != 0) {
        fprintf(stderr, "Qwen4Exp QSA rollback rebuild changed prior block (%s)\n",
                f16 ? "F16" : "F32");
        ok = 0;
    }
    pool_block_ref(expected_block, raw, f16, key_norm, 1, 1.0e-6f, rope);
    for (uint32_t d = 0; d < QSA_INDEX_DIM; d++) {
        actual_float[QSA_INDEX_DIM + d] = cache_value(
            pooled_host, QSA_INDEX_DIM + d, f16);
    }
    ok = ok && compare_values(f16 ? "rollback pool F16" : "rollback pool F32",
        actual_float + QSA_INDEX_DIM, expected_block, QSA_INDEX_DIM,
        f16 ? 1.0e-3f : 1.0e-4f);

    const float *query_norm = (const float *)
        ((const uint8_t *)model + query_norm_offset);
    const uint32_t query_position = 1048575u;
    prepare_query_ref(expected_prepared, raw_query, query_norm,
                      query_position, 1.0e-6f, rope);
    ok = ok && ds4_gpu_qwen4_exp_qsa_prepare_query_tensor(
        prepared_tensor, raw_query_tensor, model, model_size,
        query_norm_offset, query_position, 1.0e-6f, rope);
    ok = ok && ds4_gpu_tensor_read(prepared_tensor, 0, prepared,
                                   query_count * sizeof(float));
    /* CPU libm and Metal intentionally use different large-angle reduction.
     * Compare the unrotated suffix against the formula, and the rotated
     * prefix against an MLX long-context golden above. */
    for (uint32_t h = 0; h < QSA_INDEX_HEADS && ok; h++) {
        ok = compare_values(
            f16 ? "query suffix F16 run" : "query suffix F32 run",
            prepared + (uint64_t)h * QSA_INDEX_DIM + rope->n_rot,
            expected_prepared + (uint64_t)h * QSA_INDEX_DIM + rope->n_rot,
            QSA_INDEX_DIM - rope->n_rot, 2.0e-5f);
    }
    ok = ok && compare_long_yarn_golden(prepared);

    score_blocks_ref(expected_scores, prepared, pooled_host,
                     f16, QSA_BLOCKS);
    ok = ok && ds4_gpu_qwen4_exp_qsa_score_blocks_tensor(
        score_tensor, prepared_tensor, pooled_tensor, QSA_BLOCKS, f16);
    ok = ok && ds4_gpu_tensor_read(score_tensor, 0, scores,
                                   QSA_BLOCKS * sizeof(float));
    ok = ok && compare_values(f16 ? "block scores F16" : "block scores F32",
                              scores, expected_scores, QSA_BLOCKS, 5.0e-4f);

    ds4_gpu_tensor_free(score_tensor);
    ds4_gpu_tensor_free(prepared_tensor);
    ds4_gpu_tensor_free(raw_query_tensor);
    ds4_gpu_tensor_free(pooled_tensor);
    ds4_gpu_tensor_free(raw_tensor);
    free(actual_float);
    free(expected_block);
    free(expected_scores);
    free(scores);
    free(expected_prepared);
    free(prepared);
    free(raw_query);
    free(pooled_host);
    free(raw);
    return ok;
}

static uint32_t selected_token(uint32_t slot, const int32_t *blocks) {
    const uint32_t selected_tokens = QSA_SELECTED_BLOCKS * QSA_BLOCK;
    if (slot < selected_tokens) {
        return (uint32_t)blocks[slot / QSA_BLOCK] * QSA_BLOCK +
               slot % QSA_BLOCK;
    }
    const uint32_t complete_tokens = ((QSA_POSITION + 1u) / QSA_BLOCK) * QSA_BLOCK;
    return complete_tokens + slot - selected_tokens;
}

static void sparse_decode_ref(float *out, const float *query,
                              const float *gate, const void *keys,
                              const void *values, bool f16,
                              const int32_t *blocks) {
    const uint32_t tail = (QSA_POSITION + 1u) % QSA_BLOCK;
    const uint32_t n_keys = QSA_SELECTED_BLOCKS * QSA_BLOCK + tail;
    for (uint32_t head = 0; head < QSA_HEADS; head++) {
        const uint32_t kv_head = head / (QSA_HEADS / QSA_KV_HEADS);
        float scores[QSA_SELECTED_BLOCKS * QSA_BLOCK + QSA_BLOCK - 1u];
        float max_score = -INFINITY;
        for (uint32_t slot = 0; slot < n_keys; slot++) {
            const uint32_t token = selected_token(slot, blocks);
            float dot = 0.0f;
            for (uint32_t d = 0; d < QSA_HEAD_DIM; d++) {
                const uint64_t cache_index =
                    ((uint64_t)token * QSA_KV_HEADS + kv_head) *
                    QSA_HEAD_DIM + d;
                dot += query[(uint64_t)head * QSA_HEAD_DIM + d] *
                       cache_value(keys, cache_index, f16);
            }
            scores[slot] = dot / sqrtf((float)QSA_HEAD_DIM);
            max_score = fmaxf(max_score, scores[slot]);
        }
        float denom = 0.0f;
        for (uint32_t slot = 0; slot < n_keys; slot++) {
            scores[slot] = expf(scores[slot] - max_score);
            denom += scores[slot];
        }
        for (uint32_t d = 0; d < QSA_HEAD_DIM; d++) {
            float sum = 0.0f;
            for (uint32_t slot = 0; slot < n_keys; slot++) {
                const uint32_t token = selected_token(slot, blocks);
                const uint64_t cache_index =
                    ((uint64_t)token * QSA_KV_HEADS + kv_head) *
                    QSA_HEAD_DIM + d;
                sum += scores[slot] * cache_value(values, cache_index, f16);
            }
            const uint64_t out_index = (uint64_t)head * QSA_HEAD_DIM + d;
            out[out_index] = sum / denom * sigmoid_ref(gate[out_index]);
        }
    }
}

static int run_sparse_decode_test(bool f16) {
    const uint64_t head_values = (uint64_t)QSA_HEADS * QSA_HEAD_DIM;
    const uint64_t cache_values =
        (uint64_t)QSA_CACHE_CAPACITY * QSA_KV_HEADS * QSA_HEAD_DIM;
    const size_t element_bytes = f16 ? sizeof(_Float16) : sizeof(float);
    float *query = malloc((size_t)head_values * sizeof(float));
    float *gate = malloc((size_t)head_values * sizeof(float));
    void *keys = calloc((size_t)cache_values, element_bytes);
    void *values = calloc((size_t)cache_values, element_bytes);
    float *expected = malloc((size_t)head_values * sizeof(float));
    float *actual = malloc((size_t)head_values * sizeof(float));
    float *poisoned = malloc((size_t)head_values * sizeof(float));
    const int32_t selected[QSA_SELECTED_BLOCKS] = {4, 0, 2};
    if (!query || !gate || !keys || !values || !expected || !actual ||
        !poisoned) {
        fprintf(stderr, "Qwen4Exp QSA sparse decode host allocation failed\n");
        return 0;
    }
    for (uint64_t i = 0; i < head_values; i++) {
        query[i] = fixture_value(i, 11u, 1.0f / 512.0f);
        gate[i] = fixture_value(i, 13u, 1.0f / 96.0f);
    }
    for (uint64_t i = 0; i < cache_values; i++) {
        cache_store(keys, i, f16,
                    fixture_value(i, f16 ? 17u : 19u, 1.0f / 384.0f));
        cache_store(values, i, f16,
                    fixture_value(i, f16 ? 23u : 29u, 1.0f / 320.0f));
    }
    sparse_decode_ref(expected, query, gate, keys, values, f16, selected);

    ds4_gpu_tensor *query_tensor = ds4_gpu_tensor_alloc(head_values * sizeof(float));
    ds4_gpu_tensor *gate_tensor = ds4_gpu_tensor_alloc(head_values * sizeof(float));
    ds4_gpu_tensor *key_tensor = ds4_gpu_tensor_alloc(cache_values * element_bytes);
    ds4_gpu_tensor *value_tensor = ds4_gpu_tensor_alloc(cache_values * element_bytes);
    ds4_gpu_tensor *selected_tensor = ds4_gpu_tensor_alloc(sizeof(selected));
    ds4_gpu_tensor *out_tensor = ds4_gpu_tensor_alloc(head_values * sizeof(float));
    int ok = query_tensor && gate_tensor && key_tensor && value_tensor &&
             selected_tensor && out_tensor;
    ok = ok && ds4_gpu_tensor_write(query_tensor, 0, query,
                                    head_values * sizeof(float));
    ok = ok && ds4_gpu_tensor_write(gate_tensor, 0, gate,
                                    head_values * sizeof(float));
    ok = ok && ds4_gpu_tensor_write(key_tensor, 0, keys,
                                    cache_values * element_bytes);
    ok = ok && ds4_gpu_tensor_write(value_tensor, 0, values,
                                    cache_values * element_bytes);
    ok = ok && ds4_gpu_tensor_write(selected_tensor, 0, selected,
                                    sizeof(selected));
    ok = ok && ds4_gpu_qwen4_exp_qsa_decode_tensor(
        out_tensor, query_tensor, gate_tensor, key_tensor, value_tensor,
        selected_tensor, QSA_SELECTED_BLOCKS, QSA_POSITION,
        QSA_CACHE_CAPACITY, f16);
    ok = ok && ds4_gpu_tensor_read(out_tensor, 0, actual,
                                   head_values * sizeof(float));
    ok = ok && compare_values(f16 ? "sparse decode F16" : "sparse decode F32",
                              actual, expected, head_values,
                              f16 ? 1.5e-3f : 3.0e-4f);

    /* Poison every row after the committed position.  A batched verifier that
     * accidentally exposes its future tail changes this output dramatically. */
    for (uint32_t token = QSA_POSITION + 1u;
         token < QSA_CACHE_CAPACITY; token++) {
        for (uint32_t h = 0; h < QSA_KV_HEADS; h++) {
            for (uint32_t d = 0; d < QSA_HEAD_DIM; d++) {
                const uint64_t index =
                    ((uint64_t)token * QSA_KV_HEADS + h) * QSA_HEAD_DIM + d;
                cache_store(keys, index, f16, 24.0f);
                cache_store(values, index, f16, -24.0f);
            }
        }
    }
    ok = ok && ds4_gpu_tensor_write(key_tensor, 0, keys,
                                    cache_values * element_bytes);
    ok = ok && ds4_gpu_tensor_write(value_tensor, 0, values,
                                    cache_values * element_bytes);
    ok = ok && ds4_gpu_qwen4_exp_qsa_decode_tensor(
        out_tensor, query_tensor, gate_tensor, key_tensor, value_tensor,
        selected_tensor, QSA_SELECTED_BLOCKS, QSA_POSITION,
        QSA_CACHE_CAPACITY, f16);
    ok = ok && ds4_gpu_tensor_read(out_tensor, 0, poisoned,
                                   head_values * sizeof(float));
    if (ok && memcmp(actual, poisoned, head_values * sizeof(float)) != 0) {
        fprintf(stderr, "Qwen4Exp QSA %s future-tail poison changed decode\n",
                f16 ? "F16" : "F32");
        ok = 0;
    } else if (ok) {
        fprintf(stderr, "Qwen4Exp QSA %s future-tail isolation bit exact\n",
                f16 ? "F16" : "F32");
    }

    ds4_gpu_tensor_free(out_tensor);
    ds4_gpu_tensor_free(selected_tensor);
    ds4_gpu_tensor_free(value_tensor);
    ds4_gpu_tensor_free(key_tensor);
    ds4_gpu_tensor_free(gate_tensor);
    ds4_gpu_tensor_free(query_tensor);
    free(poisoned);
    free(actual);
    free(expected);
    free(values);
    free(keys);
    free(gate);
    free(query);
    return ok;
}

int main(void) {
    const uint64_t page = (uint64_t)getpagesize();
    const uint64_t key_norm_offset = 0;
    const uint64_t query_norm_offset = page;
    const uint64_t model_size = 2u * page;
    void *model = NULL;
    if (posix_memalign(&model, (size_t)page, (size_t)model_size) != 0) {
        fprintf(stderr, "Qwen4Exp QSA test model allocation failed\n");
        return 1;
    }
    memset(model, 0, (size_t)model_size);
    float *key_norm = (float *)((uint8_t *)model + key_norm_offset);
    float *query_norm = (float *)((uint8_t *)model + query_norm_offset);
    for (uint32_t d = 0; d < QSA_INDEX_DIM; d++) {
        key_norm[d] = 0.75f + 0.0025f * (float)d;
        query_norm[d] = 1.15f - 0.0015f * (float)d;
    }
    const ds4_gpu_qwen4_exp_rope_params rope = {
        .n_ctx_orig = 262144u,
        .n_rot = 64u,
        .freq_base = 10000000.0f,
        .freq_scale = 0.25f,
        .ext_factor = 1.0f,
        .attn_factor = 1.0f,
        .beta_fast = 32.0f,
        .beta_slow = 1.0f,
    };

    int ok = ds4_gpu_init() && ds4_gpu_set_model_map(model, model_size);
    ok = ok && run_indexer_test(model, model_size, key_norm_offset,
                                query_norm_offset, false, &rope);
    ok = ok && run_indexer_test(model, model_size, key_norm_offset,
                                query_norm_offset, true, &rope);
    ok = ok && run_sparse_decode_test(false);
    ok = ok && run_sparse_decode_test(true);
    ds4_gpu_cleanup();
    free(model);

    if (!ok) {
        fprintf(stderr, "Qwen4Exp QSA Metal tests FAILED\n");
        return 1;
    }
    fprintf(stderr, "Qwen4Exp QSA Metal tests PASS\n");
    return 0;
}
